import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import{BsFillMoonStarsFill} from 'react-icons/bs'
import { BiMenu } from "react-icons/bi";
import { FiSearch } from 'react-icons/fi';
import { FaBeer } from 'react-icons/fa';
import { useEffect, useState } from 'react';
import './globals.css';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className = "bg-white px-10">


        <section className="min-h-screen">

          <nav class = "py-10 mb-12 ">
            <ul id="navbar" class = "flex items-center justify-between">
                <h1 className="text-xl mr-auto">Randy Chu</h1>
                <li><a href="#" class = "hidden md:flex pl-4 pr-4">Work Experience</a></li>
                <li><a href="#" class = "hidden md:flex pl-4 pr-4">Projects</a></li>
                <li><a href="#" class = "hidden md:flex pl-4 pr-4">Contact Me</a></li>
                <li><a href="#" class = "pl-4 pr-6">Resume</a></li>
                <li><a href="#" class = "pl-6 pr-8"><BsFillMoonStarsFill/></a></li>
                <li><a id="hamburger" href="#" class = " md:hidden" ><BiMenu className= "w-10 h-10"/></a></li>
            </ul>
            </nav>

        </section>
    
      </main>
    </>
  )
}
